name: Subo docker

on:
  push:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Dockerfile'
      - .github/workflows/upload_dockerhub.yml
jobs:
  actualizacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Construyo y pusheo imagen
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USER }}/dontwait
          tags: latest